dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2

autofetch_sources: true

compiler:
  solc:
    version: 0.8.0
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2'
